name: Black Formatter test
'on':
  push:
    branches: &id001
    - main
    - master
  pull_request:
    branches: *id001
jobs:
  black:
    name: Run Black formatter
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Run Black
      uses: rickstaa/action-black@v1.3.3
      with:
        black_args: .
